language: elixir
elixir:
  - 1.0.5
  - 1.1.0-beta
sudo: false # to use faster container based build environment
otp_release:
  - 17.5
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
services:
  - rabbitmq
