language: elixir
sudo: false # to use faster container based build environment
elixir:
  - 1.4.4
otp_release:
  - 19.3
matrix:
  include:
    - elixir: 1.4.5
      otp_release: 20.0
script: mix test --exclude skip_ci
after_script:
  - mix deps.get --only docs
  - MIX_ENV=docs mix inch.report
services:
  - rabbitmq
